<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TACtaskdata [

<!-- ======================================================================
      TAC 2010 Guided Summarization task data definition

      Written 2010-06-18 by Karolina Owczarzak <karolina.owczarzak@nist.gov>
     ====================================================================== -->

    <!ELEMENT TACtaskdata  (topic+)           >
    <!ELEMENT topic       (title, docsetA, docsetB) >
    <!ELEMENT title       (#PCDATA)           >
    <!ELEMENT docsetA     (doc+)              >
    <!ELEMENT docsetB     (doc+)              >
    <!ELEMENT doc          EMPTY              >		       

    <!ATTLIST TACtaskdata
                      year    CDATA              #REQUIRED
		      track   (SUMMARIZATION)    #REQUIRED
                      task    (GUIDED)           #REQUIRED
		      dataset (SAMPLE|TEST)      #REQUIRED >

    <!ATTLIST topic  id       ID    #REQUIRED 
		     category CDATA #REQUIRED >

    <!ATTLIST docsetA  id     ID    #REQUIRED >

    <!ATTLIST docsetB  id     ID    #REQUIRED >

    <!ATTLIST doc      id     CDATA #REQUIRED >   


<!-- ====================================================================== -->
]>

<TACtaskdata year="2010" track="SUMMARIZATION" task="GUIDED"  dataset="TEST">

<topic id = "D1003A" category = "4">

	<title> Giant Panda </title>

	<docsetA id = "D1003A-A">
		<doc id = "XIN_ENG_20041019.0235" />
		<doc id = "AFP_ENG_20050128.0218" />
		<doc id = "XIN_ENG_20050210.0029" />
		<doc id = "XIN_ENG_20050213.0159" />
		<doc id = "XIN_ENG_20050216.0036" />
		<doc id = "AFP_ENG_20050216.0354" />
		<doc id = "XIN_ENG_20050222.0273" />
		<doc id = "XIN_ENG_20050327.0010" />
		<doc id = "AFP_ENG_20050328.0133" />
		<doc id = "AFP_ENG_20050329.0028" />
	</docsetA>

	<docsetB id = "D1003A-B">
		<doc id = "XIN_ENG_20050403.0018" />
		<doc id = "APW_ENG_20050410.0049" />
		<doc id = "XIN_ENG_20050415.0040" />
		<doc id = "CNA_ENG_20050503.0042" />
		<doc id = "CNA_ENG_20050504.0009" />
		<doc id = "AFP_ENG_20050507.0219" />
		<doc id = "XIN_ENG_20050511.0159" />
		<doc id = "LTW_ENG_20050709.0007" />
		<doc id = "LTW_ENG_20050709.0028" />
		<doc id = "LTW_ENG_20050709.0037" />
	</docsetB>

</topic>

</TACtaskdata>
